# Generated by Django 6.0.5 on 2026-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_rename_offersmodel_ordersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(default='in_progress', max_length=50),
        ),
    ]
