# Generated by Django 6.0.5 on 2026-05-12 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('location', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('working_hours', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
