# Generated by Django 6.0.5 on 2026-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='uploaded_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
