# Generated by Django 6.0.5 on 2026-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profilemodel_uploaded_at_alter_profilemodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
